version: '3'

services:

  my-app-prod:
    container_name: my-app-prod
    restart: on-failure #'no'  #always #on-failure
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "1337:80"
