version: '3'

services:

  my-app:
    container_name: my-app
    restart: on-failure #'no'  #always #on-failure
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app/front'
      - '/app/front/node_modules'
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
